export const GENERATE_DUB_REQUEST = 'GENERATE_DUB_REQUEST';
export const GENERATE_DUB_SUCCESS = 'GENERATE_DUB_SUCCESS';
export const GENERATE_DUB_FAILURE = 'GENERATE_DUB_FAILURE';

export const CLEAR_ERRORS = "CLEAR_ERRORS";